apiVersion: apps/v1
kind: Deployment
metadata:
  name: scd-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scd-frontend
  template:
    metadata:
      labels:
        app: scd-frontend
    spec:
      containers:
      - name: scd-frontend
        image: kaifanwar/scd_project_frontend:latest
        ports:
        - containerPort: 80