name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        & minikube docker-env | Invoke-Expression

    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t kaifanwar/scd_project:latest .

    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t kaifanwar/scd_project_frontend:latest .

    - name: Debug Docker Credentials
      run: |
        echo "Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Password: ***"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Backend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project:latest

    - name: Push Frontend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project_frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        