name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure Minikube is Running
      run: |
        Write-Output "Checking Minikube status..."
        minikube status
        if ($LASTEXITCODE -ne 0) { minikube start }

    - name: Set up Docker to use Minikube's environment
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        & minikube docker-env | Invoke-Expression
        $daemon = docker info --format '{{.Name}}'
        Write-Output "Docker daemon in use: $daemon"
        if ($daemon -ne 'minikube') { throw "Failed to set Minikube Docker daemon. Current daemon: $daemon" }

    - name: Login to Docker Hub
      run: |
        Write-Output "Logging into Docker Hub..."
        $password = "${{ secrets.DOCKER_PASSWORD }}".Trim()
        $username = "${{ secrets.DOCKER_USERNAME }}".Trim()
        Write-Output "Username: $username"
        Write-Output "Password length: $($password.Length)"
        Write-Output "Password first char: $($password[0])"
        echo $password | docker login -u $username --password-stdin
        if ($LASTEXITCODE -ne 0) { throw "Docker login failed with exit code $LASTEXITCODE" }

    - name: Build Backend Docker Image
      run: |
        Set-Location backend
        docker build -t kaifanwar/scd_project:latest .

    - name: Build Frontend Docker Image
      run: |
        Set-Location frontend
        docker build -t kaifanwar/scd_project_frontend:latest .

    - name: Push Backend Docker Image
      run: |
        docker push kaifanwar/scd_project:latest

    - name: Push Frontend Docker Image
      run: |
        docker push kaifanwar/scd_project_frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml