name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        & minikube docker-env 

    - name: Debug Docker Environment
      run: docker info --format '{{.Name}}'

    - name: Build Backend Docker image
      run: |
        Set-Location backend
        docker build -t kaifanwar/scd_project:latest .

    - name: Build Frontend Docker image
      run: |
        Set-Location frontend
        docker build -t kaifanwar/scd_project_frontend:latest .

    - name: Debug Docker Credentials
      run: |
        $username = "${{ secrets.DOCKER_USERNAME }}"
        $password = "${{ secrets.DOCKER_PASSWORD }}"
        Write-Output "Username: $username"
        Write-Output "Username Length: $($username.Length)"
        Write-Output "Password Length: $($password.Length)"
        Write-Output "Password First Char: $($password[0])"

    - name: Test Docker Login Command
      run: |
        $password = "${{ secrets.DOCKER_PASSWORD }}".Trim()
        Write-Output "Testing login with password length: $($password.Length)"
        echo $password | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Login to Docker Hub
      run: |
        Write-Output "Attempting Docker login..."
        $password = "${{ secrets.DOCKER_PASSWORD }}".Trim()
        Write-Output "Password length after trim: $($password.Length)"
        echo $password | Out-File -FilePath "docker-password.txt"
        Get-Content "docker-password.txt" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if ($LASTEXITCODE -ne 0) { throw "Docker login failed with exit code $LASTEXITCODE" }
        Remove-Item "docker-password.txt"

    - name: Push Backend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project:latest

    - name: Push Frontend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project_frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml