name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        & minikube docker-env | Invoke-Expression

    - name: Debug Docker Environment
      run: docker info --format '{{.Name}}'

    - name: Build Backend Docker image
      run: |
        Set-Location backend
        docker build -t kaifanwar/scd_project:latest .

    - name: Build Frontend Docker image
      run: |
        Set-Location frontend
        docker build -t kaifanwar/scd_project_frontend:latest .

    - name: Debug Docker Credentials
      run: |
        Write-Output "Username: ${{ secrets.DOCKER_USERNAME }}"
        Write-Output "Username Length: $(${{ secrets.DOCKER_USERNAME }}.Length)"
        Write-Output "Password Length: $(${{ secrets.DOCKER_PASSWORD }}.Length)"
        Write-Output "Password First Char: $(${{ secrets.DOCKER_PASSWORD }}[0])"

    - name: Test Docker Login Command
      run: |
        $password = "${{ secrets.DOCKER_PASSWORD }}"
        Write-Output "Testing login with password: $password"
        echo $password | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Login to Docker Hub
      run: |
        Write-Output "Attempting Docker login..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if ($LASTEXITCODE -ne 0) { throw "Docker login failed with exit code $LASTEXITCODE" }

    - name: Push Backend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project:latest

    - name: Push Frontend Docker image to Docker Hub
      run: docker push kaifanwar/scd_project_frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml